FROM python:3.11-alpine3.18

COPY requirements.txt /temp/requirements.txt

# COPY .env /.env

COPY lashes_bot/mirlashes /lashes_bot/mirlashes

ADD lashes_bot/mirlashes/manage.py lashes_bot/mirlashes

WORKDIR /lashes_bot/mirlashes

RUN pip install -r /temp/requirements.txt