services:
  mirlashes:
    build:
      context: .

    volumes:
      - ./lashes_bot:/lashes_bot

    env_file:
      - .env
    # environment:
    #   - DB_HOST=database
    #   - DB_NAME=env_file(NAME_DB)
    #   - DB_USER=env_file(USER_DB)
    #   - DB_PASS=env_file(PASS_DB)

    command: python bot.py

    depends_on:
      - database
    restart: always

  database:
    image: postgres:14.6-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: database

    expose:
      - 5432

networks:
  grid-network:
    driver: bridge
